spring:
  datasource:
    username: xxq
    password: xxq2019_
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-bp16979l63az3x58ato.mysql.rds.aliyuncs.com:3306/ecommerce?serverTimezone=Asia/Shanghai&characterEncoding=UTF-8
server:
  port: 8888
  servlet:
    session:
      timeout: 30m